export interface IUnrandItem{
	ENUM:string;
	NAME:string;
	OBJ:string;
	PLUS:string;
	TILE:string;
	TILE_EQ:string;
	COLOUR:string;
	BOOL:string;
	BASE_DELAY?:string;
	TYPE?:string;
	VALUE?:string;
	FIRE?:string;
	COLD?:string;
	MAGIC?:string;
	REGEN?:string;
	INSCRIP?:string;
	MP?:string;
	HP?:string;
	AC?:string;
	STR?:string;
	INT?:string;
	DEX?:string;
	LIFE?:string;
	BRAND?:string;
	FB_BRAND?:string;
	EV?:string;
	ANGRY?:string;
}